pro2/pro2/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from app2.views import model_form_upload, contact_page
from .views import login_page,home_page, logout_page,dept
from django.conf import settings
from django.conf.urls.static import static
from subjects.views import Books, Articles, Papers, cse_watch,ece_watch,it_watch, read

urlpatterns = [
    url(r'^$',home_page,name="home"),
    url(r'^upload/$',model_form_upload,name='upload'),
    url(r'^login/$',login_page,name="login"),
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^logout/$',logout_page,name="logout"),
    url(r'^books/$',Books,name="books"),
    url(r'^articles/$',Articles,name="articles"),
    url(r'^papers/$',Papers,name="papers"),
    url(r'^cse_watch/$',cse_watch,name="cse_watch"),
    url(r'^ece_watch/$',ece_watch,name="ece_watch"),
    url(r'^it_watch/$',it_watch,name="it_watch"),
    url(r'^read/$',read,name="read"),
    url(r'^dept/$',dept,name="dept"),
    url(r'^contact/$',contact_page,name="contact"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pro2/search/urls.py
from django.conf.urls import url

from django.conf.urls import include

from .views import (searchposts)
app_name = 'search'
urlpatterns = [
    url(r'^$', searchposts, name='searchposts'),

]

pro2/templates/snippets/cs.html
{% load staticfiles %}


<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

pro2/templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

pro2/templates/snippets/navbar.html
{% url 'login' as login_url%}
{% url 'logout' as logout_url%}
{% url 'upload' as upload_url%}
{% url 'contact' as contact_url%}
{% url 'dept' as dept_url%}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#"><b>DIGI LIBRARY</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/"><b>Home </b><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/"><b>About</b></a>
      </li>
      <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{{ contact_url }}"><b>Contact</b></a>
                  </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{{ dept_url }}"><b>Department</b></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ logout_url }}"><b>Logout</b></a>
      </li>
      {% if request.session.rolename == "staff" %}
      <li class="nav-item">
        <a class="nav-link" href="{{ upload_url }}"><b>Upload</b></a>
      </li>
      {% endif %}
{% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ login_url }}"><b>Login</b></a>
        </li>


{% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search:searchposts' %}" value="{{request.GET.q}}">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{request.GET.q}}">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>


  </div>
</nav>